"""empty message

Revision ID: 2c68328fe2f8
Revises: 
Create Date: 2024-07-15 14:45:05.972136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c68328fe2f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
